//PORT NO
#define PORT_NO 8082


#define INITIAL_PROMPT "Welcome to bank apllication!\nlogin as: (Enter your choice)\n1. Admin\t2. Customer\t3. Manager \t4. Bank employee\nPress any other number to exit\nEnter the number corresponding to the choice!\n"

#define ADMIN_LOGIN_WELCOME_MSG "Welcome Admin! \nEnter your credentials to unlock !"
#define ADMIN_LOGIN_SUCCESS "Welcome Admin!"


// ADMIN MENU
#define ADMIN_MENU "1.Add Customer\n  2. Get Customer Details\n3. Get Account Details\n4. Get Transaction details\n5. Add Account\n6. Delete Account\n7. Modify Customer Information\n 8. temp braek while loop\n Press any other key to logout"


//ADD CUSTOMER
///#define ADMIN_ADD_CUSTOMER_PRIMARY "Enter the details for the primary customer\n"
//#define ADMIN_ADD_CUSTOMER_SECONDARY "Enter the details for the secondary customer\n"
#define ADMIN_ADD_CUSTOMER_NAME "Enter Customer name"
#define ADMIN_ADD_CUSTOMER_GENDER "Enter Customer gender F,M or O (only)"
#define ADMIN_ADD_CUSTOMER_AGE "What is the customer's age?"
//#define ADMIN_ADD_CUSTOMER_AUTOGEN_LOGIN "The autogenerated login ID for the customer is : "
///#define AUTOGEN_PASSWORD "spookytime" // append to end of next string macro
#define ADMIN_ADD_CUSTOMER_AUTOGEN_PASSWORD "The autogenerated password for the customer is : "
#define ADMIN_ADD_CUSTOMER_WRONG_GENDER "It seems you've enter a wrong gender choice!\nYou'll now be redirected to the main menu!^"
#define ADMIN_ADD_ACCOUNT_NUMBER "Enter customer account number"
#define ADMIN_ADD_EMAIL_ID "Enter customer Email Address"
//RESULT 
#define LOGIN_ID_IS "Your Login id is:"
#define LOGIN_PASS_IS "Your Login Password is:"
#define LOGIN_SUCCESSFULL_MSG "Login is done successfully!!"


// LOGIN
#define LOGIN_ID_MSG "Enter your login ID\n"
#define PASSWORD_MSG "Enter your password \n# "
#define INVALID_LOGIN_MSG "The login ID specified doesn't exist!$"
#define INVALID_PASSWORD_MSG "The password specified doesn't match!$"


//SALT
#define HASH_SIZE 64